### ISSUE TITLE
newrelic install command doesn't respect the HTTPS_PROXY env variable

### ISSUE THREAD

**Issue by aschmid13** [newrelic/open-install-library#483]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
`newrelic install` fails due to HTTPS_PROXY not passing through to the installer.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Run `newrelic install` in an environment where a proxy is needed. It will fail at this step:
```
sudo curl -s $REPO_URL -o /etc/yum.repos.d/newrelic-infra.repo
```

With this error message:

```
execution failed for infrastructure-agent-installer: exit status 7\",\"details\":\"\",\"taskPath\":[\"default\",\"install_infra\"]},\"logFilePath\":\"/root/.newrelic/newrelic-cli.log\",\"recipes\":[{\"displayName\":\"Infrastructure Agent\",\"error\":{\"message\":\"execution failed for infrastructure-agent-installer: exit status 7
```

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

Expected to utilize the proxy and run successfully. Using yum to install succeeds on the same machine with Proxy set.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Operating System and version: CentOS 7

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/centos_rhel.yml#L147

**Comment by rthorn-nr** [comment]
Hi @aschmid13 , we have addressed CentOS failures behind a proxy as of newrelic-cli [v0.65.1](https://github.com/newrelic/newrelic-cli/releases/tag/v0.65.1) -- [diff](https://github.com/newrelic/open-install-library/pull/882/files#diff-359c7ef385986e631d9023383ad1c70e2bff6d3bfe755139ec4f9cbe4ceab377R164-R170)

yum/dnf needs to be configured alongside using `HTTPS_PROXY` by setting `proxy=` in the dnf config file /etc/dnf/dnf.conf -- [more info](https://dnf.readthedocs.io/en/latest/conf_ref.html?highlight=proxy)

This behavior has been tested on CentOS 8. Acknowledging it has been a while since you raised this bug, please let me know if you run into further issues
